{{- if .Values.metrics.serviceMonitor.enabled }}
{{- if not .Values.metrics.enabled }}
{{- fail "You enabled metrics.serviceMonitor.enabled, but metrics.enabled is false. Please enable metrics to use the ServiceMonitor." }}
{{- end }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "node-readiness-controller.fullname" . }}
  namespace: {{ include "node-readiness-controller.namespace" . }}
  labels:
    {{- include "node-readiness-controller.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "node-readiness-controller.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ ternary "https" "http" .Values.metrics.secure }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      {{- if .Values.metrics.secure }}
      scheme: https
      {{- if .Values.metrics.serviceMonitor.bearerTokenFile }}
      bearerTokenFile: {{ .Values.metrics.serviceMonitor.bearerTokenFile }}
      {{- else }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
