  kind: Cluster
  apiVersion: kind.x-k8s.io/v1alpha4
  name: nrc-kubelet-cert-demo
  nodes:
    - role: control-plane
      kubeadmConfigPatches:
        - |
          kind: KubeletConfiguration
          apiVersion: kubelet.config.k8s.io/v1beta1
          serverTLSBootstrap: true
    - role: worker
      kubeadmConfigPatches:
        - |
          kind: JoinConfiguration
          nodeRegistration:
            kubeletExtraArgs:
              register-with-taints: "readiness.k8s.io/KubeletServingCertNotReady=pending:NoSchedule"